name: CI

on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  # allows to run manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2020b
          products: Deep_Learning_Toolbox Parallel_Computing_Toolbox
        
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v2
        with:
          source-folder: src
          select-by-folder: test
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          
      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: test-results/results.xml
          
      - name: Code Coverage Summary Report
        uses: codecov/codecov-action@v4
        if: always()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: code-coverage/coverage.xml
